sudo: required # Necessary when using Docker

language: cpp

compiler: gcc

services:
  - docker

install:
  - travis_wait 45 docker pull greenblattryan/ctrelinuxbase:latest

script:
  - docker run --user ubuntu greenblattryan/ctrelinuxbase:latest /bin/bash -l -c
    "cd ~ &&
     git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2018RobotCode/ &&
     cd ./2018RobotCode/ &&
     git checkout $TRAVIS_COMMIT &&
     git log -n1 &&
     git submodule update --init --recursive &&
     ./install_ros_desktop_packages.sh &&
     cd zebROS_ws &&
     wstool update -t src &&
     source /opt/ros/kinetic/setup.bash &&
     catkin_make &&
     echo \"Finished Ubuntu compile.\""
build:
  - true

notifications:
  email: false

