sudo: required # Necessary when using Docker

language: cpp

compiler: gcc

services:
  - docker

install:
  - travis_wait 45 docker pull greenblattryan/ctrelinuxbase:latest

script:
  - docker run greenblattryan/ctrelinuxbase:latest /bin/bash -l -c
    "git clone https://github.com/rgreenblatt/native-samples &&
     cd ./native-samples &&
     git checkout $TRAVIS_COMMIT &&
     echo COMMIT &&
     echo $TRAVIS_COMMIT &&
     echo COMMITMSG &&
     echo $TRAVIS_COMMIT_MESSAGE &&
     echo BRANCH &&
     echo $TRAVIS_BRANCH &&
     git log -n1 &&
     ./gradlew build &&
     echo \"Finished Ubuntu compile.\"
     echo \"Finished Travis.\""
build:
  - true

notifications:
  email: false

